// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCdAvHXKwTA-LXc01IjD0Oko56zu7M7aY',
    appId: '1:442278868539:web:107b77656eab105996ce1e',
    messagingSenderId: '442278868539',
    projectId: 'rapid-aid-48ab9',
    authDomain: 'rapid-aid-48ab9.firebaseapp.com',
    storageBucket: 'rapid-aid-48ab9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJFDFM4MtfFhuve8bHh0iYSB9SuZ5CNkM',
    appId: '1:442278868539:android:b5ddfb79aef3da1a96ce1e',
    messagingSenderId: '442278868539',
    projectId: 'rapid-aid-48ab9',
    storageBucket: 'rapid-aid-48ab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVL6Zpm-EUot1yxK2Rm9ECs_JBkbXRr_Q',
    appId: '1:442278868539:ios:739b3fe7469726d096ce1e',
    messagingSenderId: '442278868539',
    projectId: 'rapid-aid-48ab9',
    storageBucket: 'rapid-aid-48ab9.firebasestorage.app',
    iosBundleId: 'com.example.rapidAid',
  );
}
